# Site settings
title: "Close Talkers: A Seinfeld Podcast!"
author:
  name: Close Talkers
  email: closetalkerspod@gmail.com
description: "Derek and Katy are a married couple who are (re-)watching Seinfeld start to finish. One of us can recite every word. The other hasn't seen it. Come laugh with us!"

# Build settings
remote_theme: jekyll/minima
